USE [master]
GO

/****** Object:  Database [App_gym]    Script Date: 20/02/2022 2:59:45 p. m. ******/
CREATE DATABASE [App_gym]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'App_gym', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\App_gym.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'App_gym_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\App_gym_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [App_gym].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [App_gym] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [App_gym] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [App_gym] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [App_gym] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [App_gym] SET ARITHABORT OFF 
GO

ALTER DATABASE [App_gym] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [App_gym] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [App_gym] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [App_gym] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [App_gym] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [App_gym] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [App_gym] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [App_gym] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [App_gym] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [App_gym] SET  DISABLE_BROKER 
GO

ALTER DATABASE [App_gym] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [App_gym] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [App_gym] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [App_gym] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [App_gym] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [App_gym] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [App_gym] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [App_gym] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [App_gym] SET  MULTI_USER 
GO

ALTER DATABASE [App_gym] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [App_gym] SET DB_CHAINING OFF 
GO

ALTER DATABASE [App_gym] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [App_gym] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [App_gym] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [App_gym] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [App_gym] SET QUERY_STORE = OFF
GO

ALTER DATABASE [App_gym] SET  READ_WRITE 
GO


