USE [App_gym]
GO

/****** Object:  Table [dbo].[CLIENTE]    Script Date: 20/02/2022 2:57:09 p. m. ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CLIENTE](
	[CEDULA] [bigint] NOT NULL,
	[NOMBRE] [varchar](100) NULL,
	[TELEFONO] [bigint] NULL,
	[OCUPACION] [varchar](150) NULL,
 CONSTRAINT [CLIENTE_PK] PRIMARY KEY CLUSTERED 
(
	[CEDULA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


