USE [App_gym]
GO

/****** Object:  Table [dbo].[MENSUALIDAD]    Script Date: 20/02/2022 2:58:17 p. m. ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[MENSUALIDAD](
	[NROREGISTRO] [bigint] NOT NULL,
	[FECHA_INICIO] [date] NULL,
	[FECHA_FIN] [date] NULL,
	[COSTO] [bigint] NULL,
	[CEDULA] [bigint] NOT NULL,
 CONSTRAINT [MENSUALIDAD_PK] PRIMARY KEY CLUSTERED 
(
	[NROREGISTRO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[MENSUALIDAD]  WITH CHECK ADD  CONSTRAINT [MENSUALIDAD_FK] FOREIGN KEY([CEDULA])
REFERENCES [dbo].[CLIENTE] ([CEDULA])
GO

ALTER TABLE [dbo].[MENSUALIDAD] CHECK CONSTRAINT [MENSUALIDAD_FK]
GO


