USE [App_gym]
GO

/****** Object:  Table [dbo].[COMPRAS]    Script Date: 20/02/2022 2:57:37 p. m. ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[COMPRAS](
	[CEDULA] [bigint] NOT NULL,
	[ID] [bigint] NOT NULL,
	[FECHA] [date] NULL,
	[CODIGO_COMPRA] [bigint] NOT NULL,
 CONSTRAINT [COMPRAS_PK] PRIMARY KEY CLUSTERED 
(
	[CODIGO_COMPRA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[COMPRAS]  WITH CHECK ADD  CONSTRAINT [COMPRAS_FK1] FOREIGN KEY([CEDULA])
REFERENCES [dbo].[CLIENTE] ([CEDULA])
GO

ALTER TABLE [dbo].[COMPRAS] CHECK CONSTRAINT [COMPRAS_FK1]
GO

ALTER TABLE [dbo].[COMPRAS]  WITH CHECK ADD  CONSTRAINT [COMPRAS_FK2] FOREIGN KEY([ID])
REFERENCES [dbo].[ARTICULO] ([ID])
GO

ALTER TABLE [dbo].[COMPRAS] CHECK CONSTRAINT [COMPRAS_FK2]
GO


